name: Build Channels

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: [master, dev, beta, stable]
        include:
          - channel: master
            tags: [master]
          - channel: dev
            tags: [dev]
          - channel: beta
            tags: [beta]
          - channel: stable
            tags: [stable, latest]
    steps:
      - uses: actions/checkout@v2
      - name: setup buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        run: |
          docker build \
            -t fischerscode/flutter:${{ join(matrix.tags, ' -t fischerscode/flutter:') }} \
            --build-arg=flutterVersion=${{ matrix.channel }} \
            --cache-from=type=registry,ref=fischerscode/flutter-cache:${{ matrix.channel }} \
            --cache-to=type=registry,ref=fischerscode/flutter-cache:${{ matrix.channel }},mode=max \
            --push \
            .
