name: Build Branches

on:
  push:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  fetch-branches:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.fetch-refs.outputs.matrix }}
    steps:
      - id: fetch-refs
        run: |
          curl -s https://api.github.com/repos/flutter/flutter/git/refs/heads > heads.json
          matrix=$(curl -s https://api.github.com/repos/flutter/flutter/commits | jq 'map(.sha) | .[]' | xargs -L1 -I KEY sh -c "cat heads.json | jq '.[] | select(.object.sha==\"KEY\")'" | jq -s 'map(.ref) | map(sub("refs/heads/"; ""))' | jq -c '{channel: . , include: map({channel:  . , tags: [ if . == "stable" then ., "latest" else . end ]})}')
          echo "::set-output name=matrix::$matrix"
  build-branches:
    needs: fetch-branches
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.fetch-branches.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: setup buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        run: |
          docker build \
            -t fischerscode/flutter:${{ join(matrix.tags, ' -t fischerscode/flutter:') }} \
            --build-arg=flutterVersion=${{ matrix.channel }} \
            --cache-from=type=registry,ref=fischerscode/flutter-cache:${{ matrix.channel }} \
            --cache-to=type=registry,ref=fischerscode/flutter-cache:${{ matrix.channel }},mode=max \
            --push \
            .
