name: Build Tags

on:
  push:
  schedule:
    - cron: "0 * * * *"
    - cron: "20 * * * *"
    - cron: "40 * * * *"
  workflow_dispatch:

jobs:
  fetch-tags:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.fetch-refs.outputs.matrix }}
    steps:
      - id: fetch-refs
        run: |
          curl -s https://hub.docker.com/v2/repositories/fischerscode/flutter/tags | jq '.results | map(.name)' > dockerhub-tags.json
          matrix=$(curl -s https://api.github.com/repos/flutter/flutter/git/refs/tags | jq 'map(.ref) | map(sub("refs/tags/"; "")) | .[]' | xargs -L1 -I TAG sh -c "cat dockerhub-tags.json | jq 'select(all(.[]; .==\"TAG\" | not)) | \"TAG\"'" | jq -s '.[:20]' | jq -c '{channel: . , include: map({channel:  . , tags: [ if . == "stable" then ., "latest" else . end ]})}')
          echo "::set-output name=matrix::$matrix"
  build-tags:
    needs: fetch-tags
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.fetch-tags.outputs.matrix)}}
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: setup buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        run: |
          docker build \
            -t fischerscode/flutter:${{ join(matrix.tags, ' -t fischerscode/flutter:') }} \
            --build-arg=flutterVersion=${{ matrix.channel }} \
            --cache-from=type=registry,ref=fischerscode/flutter-cache:${{ matrix.channel }} \
            --cache-to=type=registry,ref=fischerscode/flutter-cache:${{ matrix.channel }},mode=max \
            --push \
            --platform linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x \
            -f Dockerfile.tags \
            .
