name: stable

on:
  push:

jobs:
  stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag fischerscode/flutter:stable --build-args flutterVersion=stable
