name: stable

on:
  push:

jobs:
  stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag fischerscode/flutter:stable --build-arg flutterVersion=stable

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        run: |
          docker push fischerscode/flutter:stable
          docker tag fischerscode/flutter:stable fischerscode/flutter:latest
          docker push fischerscode/flutter:latest
